defaultLang: pl_PL
startPoints: 500

guildCreatingEnabled: true

guildValidity:
  minutes: 0
  hours: 0
  days: 0
  months: 1

noForeignInteractions:
  - chest
  - ender_chest
  - lever

chatVariables:
    rank: "{@RANK}"

    guildTag: "{@TAG}"
    guildName: "{@NAME}"
    guildRank: "{@GRANK}" #TODO
    guildLives: "{@GLIVES}" #TODO

blocksCanBeDestroyedByTnt: #you can add your own blocks, and the chance of an explosion
  obsidian: 50
  enchanting_table: 10
  #water: 90
  #lava: 90

minDistanceToSpawn: 250
minDistanceBetweenGuilds: 50

allowedWorlds:
  - world

guildRender:
  tagMinLength: 1
  tagMaxLength: 5
  nameMinLength: 2
  nameMaxLength: 10

  tagBlackList: #TODO
    - "fuck"
    - "bpl" #XD

  nameWordsBlackList: #TODO guild name cannot cointains this words
    - "fuck"
    - "kurwa"

eloMultiplier: 30

privateChatPrefix: "!"
privateChatFormat: "&6[&c!&6]&7{0}:&f {1}"

blackListCommandsInGuildRegion:
  - "sethome"

#TODO
regionsEnabled: true
tntExplosionInGuildCooldown: 120s

minMembersInGuildToSeeRank: 2

#TODO
#ENDERCRYSTALE MAJA BYC ZROBIONE PAKIETAMI
#DUMMY Z RANKIEM
#PODBIJANIE GILDII
#kOMENDY ADMINA
#MAKSYMALNA ILOSC GRACZY W GILDII, sojuszy i wrogow
#TOPKA RANKINGU
#INFO GRACZA TO KD I RANKING
#POTRZEBNE ITEMY DO ZALOZENIA GILDII