# BASIC
defaultLang: pl_PL
guildCreatingEnabled: true
canAttackGuildMembers: false
canAttackGuildFriends: false
tpCooldown: 5 #seconds

# RANK
startPoints: 500
eloMultiplier: 30
minMembersInGuildToSeeRank: 2 #TODO

# GUILD CREATION SETTINGS
minDistanceToSpawn: 250
minDistanceBetweenGuilds: 50
minDistanceFromBorder: 100
allowedWorlds:
  - world

guildRender:
  tagMinLength: 1
  tagMaxLength: 5
  nameMinLength: 2
  nameMaxLength: 10
  tagBlackList:
    - "fuck"
  nameBlackList:
    - "fuck"
    - "kurwa"
  descriptionBlackList:
    - "kurwa"

guildValidity:
  minutes: 0
  hours: 0
  days: 0
  months: 1

# GUILD REGION
regionsEnabled: true #TODO
regionSize: 25
GuildtntExplosionCooldown: 120s #TODO
noForeignInteractions:
  - chest
  - ender_chest
  - lever

blackListCommandsInGuildRegion:
  - "sethome"

# CHAT
chatVariables:
    rank: "{@RANK}"

    guildTag: "{@TAG}"
    guildName: "{@NAME}"
    guildRank: "{@GRANK}" #TODO
    guildLives: "{@GLIVES}" #TODO

privateChatPrefix: "!" 
privateChatFormat: "&6[&c!&6]&7{0}:&f {1}"

# OTHER
guildSafeName: "&6{0} - {1}"
guildSafeSize: 27

blocksCanBeDestroyedByTnt:
  #Material:chance
  obsidian: 50
  enchanting table: 10
  water: 90
  lava: 90

creationItems:
  enabled: true #TODO
  items:
    vip:
      diamond: 10
      grass block: 10
    player:
      diamond: 20
      grass block: 10