defaultLang: pl_PL
startPoints: 500
guildValidity:
  minutes: 0
  hours: 0
  days: 0
  months: 1
guildRender:
  tagMinLengh: 1
  tagMaxLengh: 5
  nameMinLengh: 2
  nameMaxLengh: 10

MinDistanceBetweenGuilds: 50
MinDistanceBetweenSpawn: 250