defaultLang: pl_PL
startPoints: 500

guildCreatingEnabled: true

guildValidity:
  minutes: 0
  hours: 0
  days: 0
  months: 1

noForeignInteractions:
  - chest
  - ender_chest
  - lever

chatVariables:
    rank: "{@RANK}"

    guildTag: "{@TAG}"
    guildName: "{@NAME}"
    guildRank: "{@GRANK}" #TODO
    guildLives: "{@GLIVES}" #TODO

minDistanceToSpawn: 250
minDistanceBetweenGuilds: 50

allowedWorlds:
  - world

guildRender:
  tagMinLength: 1
  tagMaxLength: 5
  nameMinLength: 2
  nameMaxLength: 10

  tagBlackList: #TODO
    - "example"

  nameBlackList: #TODO
    - "example name"

#TODO
regionsEnabled: true
tablistEnabled: true
tntExplosionInGuildCooldown: 120s

minMembersInGuildToSeeRank: 2

#ENDERCRYSTALE MAJA BYC ZROBIONE PAKIETAMI
#DUMMY Z RANKIEM
#NISZCZENIE BLOKOW PRZEZ TNT + uwzglednienie szansy na to
#PODBIJANIE GILDII
#kOMENDY ADMINA
#MAKSYMALNA ILOSC GRACZY W GILDII, sojuszy i wrogow
#PRYWATNY CZAT GILDII
#TOPKA RANKINGU
#INFO GRACZA TO KD I RANKING
#POTRZEBNE ITEMY DO ZALOZENIA GILDII