name: Guilds
version: 0.5
main: me.sewer.guilds.GuildsPlugin
api-version: 1.14
load: POSTWORLD
website: https://github.com/Sewer-47/Guilds
softdepend:
  - PlaceholderAPI
authors:
  - Sewer
commands:
  guild:
    usage: Guilds impl
    aliases:
      - g
      - gildia
      - gildie